
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        CATEGORY_ADD_NEW: "CATEGORY_ADD_NEW",
        PRODUCT_ADD_NEW: "PRODUCT_ADD_NEW",
        CONFIRMATION: "CONFIRMATION",
        SELECT_CHARACTER_ITEMS: "SELECT_CHARACTER_ITEMS",
        DEFAULT: "",

    },
    RIGHT_OFFCANVAS: {
      SHOW_OFFCANVAS:"SHOW_OFFCANVAS",
    //   CLOSE_OFFCANVAS:"CLOSE_OFFCANVAS",

    },
    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        CALENDAR_EVENTS: "CALENDAR_EVENTS",
        OFFCANVAS:"OFFCANVAS"
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        LEAD_DELETE: "LEAD_DELETE",
    },
});
