
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        CATEGORY_ADD_NEW: "CATEGORY_ADD_NEW",
        PRODUCT_ADD_NEW: "PRODUCT_ADD_NEW",
        TOP_CATEGORY_ADD_NEW: "TOP_CATEGORY_ADD_NEW",
        TOP_PRODUCT_ADD_NEW: "TOP_PRODUCT_ADD_NEW",
        BANNER_ADD_NEW: "BANNER_ADD_NEW",
        CONFIRMATION: "CONFIRMATION",
        SELECT_CHARACTER_ITEMS: "SELECT_CHARACTER_ITEMS",
        DEFAULT: "",

    },
    RIGHT_OFFCANVAS: {
        SHOW_OFFCANVAS: "SHOW_OFFCANVAS",

    },
    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        OFFCANVAS: "OFFCANVAS",
        OFFCANVASPROPOSAL: "OFFCANVASPROPOSAL"
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        CATEGORY_DELETE: "CATEGORY_DELETE",
        TOP_CATEGORY_DELETE: "TOP_CATEGORY_DELETE",
        PRODUCT_DELETE: "PRODUCT_DELETE",
        BANNER_DELETE: "BANNER_DELETE",
    },
});
